import Head from "next/head";
import ContactForm from "components/ContactForm/ContactForm";

export default function Contact() {

  return (
    <>
      <Head>
        <title>Contact - Julius Djudjaku</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ marginTop: "170px",marginBottom: '100px', width: '80%', display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center'}}>
        <h1>Want to get in touch ?</h1>
        <br/>
        <h3>Fill out the form and I will get back to you as soon as possible.</h3>
      <ContactForm/>
      </div>
    </>
  );
}
