import Head from "next/head";
import s from "../styles/CV.module.css";
import jobs from "data/jobs";
import TimelineCard from "components/TimelineCard/TimelineCard";

export default function CV() {
  return (
    <>
      <Head>
        <title>About me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={s.parent}>
        <div className={s.cirkel}>
          <h1>About me</h1>
          <p style={{color: 'orange', fontSize: '100px', position: 'absolute', right: '-50px'}}>.</p>
        </div>

        <div className={s.rubrik}>
          <h1>Timeline</h1>
        </div>
      </div>

      <div className={s.timeline}>
        {jobs && jobs.map((job) => {
          return (
            <TimelineCard key={job.name} job={job}/>
          )
        })}
        
      </div>
    </>
  );
}
