import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/General.module.css";
import julius from "../../public/julius.jpg";
import useMediaQuery from "@mui/material/useMediaQuery";
import projects from "data/projects";
import ProjectCard from "components/ProjectCard/ProjectCard";
import GitHubIcon from "@mui/icons-material/GitHub";


export default function Home() {
  const isMobile = useMediaQuery("(max-width:574px)");
  const isTablet = useMediaQuery("(max-width:875px)");
  return (
    <>
      <Head>
        <title>JuLius.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/JD.png" />
      </Head>
      <section
        className={isTablet || isMobile ? styles.introMobileTablet : styles.introFullScreen}
      >
        <div
          className={
            isTablet ? styles.helloContainerTabletMobile : styles.helloContainer
          }
        >
          <h1 style={{ fontSize: isMobile || isTablet ? '35px' : '50px' }}>Hello there!👋</h1>
          <h3>
            My name is Julius Djudjaku and I am soon to be a gratuated web
            developer. I'm currently a student at Medieinstitutet in gothenburg
            where im studying fullstack web developer. Right now Im doing my last internship at the gothenburg based e-commerce agency
Wallmander & co.  {" "}
          </h3>
          <h3>
            My skills range from front end (html, css, javascript/ts, react & next.js) to
            basic knowledge in back-end (php, node.js, MYSQL).
          </h3>
        </div>
        <Image
          src={julius}
          alt={"julius"}
          width={250}
          height={250}
          style={{ borderRadius: "50%", border: "1px solid #1B1B1B" }}
        />
      </section>

      {/* /* PROJECS SECTION */}

      <div id="projects" className={styles.projectsFullWidthContainer}>
        <section className={styles.projectsContainer}>
          <h1 style={{ fontSize: "50px" }}>Projects</h1>
          {projects && projects.map((project) => {
            return (
              <ProjectCard key={project.name} project={project} />
            )
          })}
        </section>
      </div>
    </>
  );
}
